### ISSUE TITLE
Project 1 - Peer Review : 

### ISSUE THREAD

**Issue by RutujaJadhav19** [airavata-courses/CloudElves#51]
Hello CloudElves team,

I ran your application in my local and I was able to run all the containers. The application works well and I was able to sign in and view the plots. Overall great work. I just have a couple of pointers :

1) You'll can implement continuous Integration for pushing docker images to docker hub and then using them to start your containers. It makes the setup easy andless time-consuming.
2) UI can be enhanced a little more.

Wish you all the best in your upcoming projects.

Team Scapsulators : https://github.com/airavata-courses/scapsulators

**Comment by ayushsanghavi** [comment]
Hello Team Scapsulators,
Thank you for the feedback :)
1) Yes, we shall do the needful for the upcoming milestone, really liked the part where you guys only had to run 1 docker file that had a lot of other containers set up sequentially.
2) Yes, we didn't pay much heed to the UI since foundation needed to be strong. In the upcoming, milestones, we definitely plan to improve UI and add more frontend features.

--Team CloudElves.
